### PR TITLE
refactor: refactor to add config file support

### PR DESCRIPTION
**Pull request by sammcj**
I've done a significant refactor to uplift the code and add config file support.

- Added support for reading defaults from a config file.
	- Add command to generate a config file with defaults.
	- Document the new functionality.
- Added support for updating existing downloaded models if newer files or versions are available.
- Remove the need for os/exec.
- Lint and fix markdown errors, spelling mistakes in readme and code.
- Colourisation of output/warnings/errors.
- Added `-j` or `justDownload` which takes takes one argument of a model's repo (e.g. `user/model`) and just downloads to the current directory it without having to specify --storage or -m.
- Bump version to 1.3.2.

### CODE REVIEW

**Comment by sammcj** [comment]
Fixes #24

**Comment by sammcj** [comment]
Added support for updating existing downloaded models if newer files or versions are available.

**Comment by bodaay** [comment]
Awesome man, before I merge this one, don't you think we need to change the parameters names, I kept adding new ones and some of them they don't make any sense now.

**Comment by sammcj** [comment]
I think they could do with a cleanup yeah, but it’s not terrible.

I have a few more ideas too but I’m away until later next week.

**Comment by sammcj** [comment]
Updated to add:

- Colourisation of output/warnings/errors.
- Added `-j` or `justDownload` which takes takes one argument of a model's repo (e.g. `user/model`) and just downloads to the current directory it without having to specify --storage or -m.

**Comment by sammcj** [comment]
ping @bodaay

**Comment by bodaay** [comment]
This is awesome man, thanks for the hardwork and sorry about the super late response

**Comment by sammcj** [comment]
:)

**Pull request merged**
